language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r-packages:
- rjson
- testthat
- knitr

r_check_args: --no-build-vignettes --no-vignettes


r_github_packages:
  - jokergoo/GlobalOptions
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'

